H0:Dice is fair
Ha:Diceis not fare

In [1]:
from scipy.stats import chi2
import numpy as np


In [12]:
df=6-1
ls=0.05

In [3]:
OBD=np.array([22,17,20,26,22,13])
EXP=np.array([20,20,20,20,20,20])

In [7]:
chi_sqr_cal=np.sum(np.square(OBD-EXP)/EXP)
chi_sqr_cal

5.1000000000000005

In [13]:
chi_sqr_table=chi2.ppf(1-ls,df)
chi_sqr_table

11.070497693516351

In [14]:
if chi_sqr_cal>chi_sqr_table:
    print("Ha is right")
else:
    print("H0 is right")    

H0 is right


H0:No assiciation
Ha:assication

In [15]:
row1=np.array([40,45,25,10])
row2=np.array([30,35,20,30])

In [19]:
sum_row1=np.sum(row1)
sum_row2=np.sum(row2)
sum_row=np.array([sum_row1,sum_row2])
sum_row


array([120, 115])

In [17]:
sum_cl=row1+row2
sum_cl

array([70, 80, 45, 40])

In [21]:
exp=[]
for i in sum_row:
    for j in sum_cl:
        value=(i*j)/235
        exp.append(value)
exp

[35.744680851063826,
 40.851063829787236,
 22.97872340425532,
 20.425531914893618,
 34.255319148936174,
 39.148936170212764,
 22.02127659574468,
 19.574468085106382]

In [23]:
obs=np.array([40,45,25,10,30,35,20,30])
obs

array([40, 45, 25, 10, 30, 35, 20, 30])

In [24]:
chi_sqr_cal2=np.sum(np.square(obs-exp)/exp)
chi_sqr_cal2

13.133689541637914

In [25]:
row=2
col=4
df=(row-1)*(col-1)
df


3

In [26]:
chi_sqr_table2=chi2.ppf(1-ls,df)
chi_sqr_table2

7.814727903251179

In [27]:
if chi_sqr_cal2>chi_sqr_table2:
    print("Ha is right")
else:
    print("H0 is right") 

Ha is right
