In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]

In [3]:
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape

(5,)

In [6]:
lst1=[1,2,3,4,5]
lst2=[6,7,8,9,10]
lst3=[11,12,13,14,15]

arr1=np.array([lst1,lst2,lst3])

In [7]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
arr1.shape

(3, 5)

In [9]:
#indexing
arr[3]

np.int64(4)

In [10]:
arr[0]=0
arr

array([0, 2, 3, 4, 5])

In [11]:
arr[1:4]

array([2, 3, 4])

In [12]:
arr[-1]

np.int64(5)

In [13]:
arr[::-1]

array([5, 4, 3, 2, 0])

In [14]:
arr[::]

array([0, 2, 3, 4, 5])

In [15]:
arr[::-2]

array([5, 3, 0])

In [16]:
arr[-1:-2]

array([], dtype=int64)

In [17]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
arr1[:,1]

array([ 2,  7, 12])

In [19]:
arr1[1:,1:3]

array([[ 7,  8],
       [12, 13]])

In [20]:
arr1[0:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [21]:
arr1[0:,2:5].shape

(3, 3)

In [22]:
arr1[:, [0, -1]]

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])

In [23]:
arr[arr<2]

array([0])

In [24]:
arr1


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [26]:
np.arange(1,20,2).reshape(10,1)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [27]:
np.arange(1,20,2).reshape(10,1,1)

array([[[ 1]],

       [[ 3]],

       [[ 5]],

       [[ 7]],

       [[ 9]],

       [[11]],

       [[13]],

       [[15]],

       [[17]],

       [[19]]])

In [28]:
arr*arr

array([ 0,  4,  9, 16, 25])

In [29]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [30]:
arr1*arr1

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.random.randint(1,10,4).reshape(2,2)

array([[8, 4],
       [6, 6]], dtype=int32)

In [34]:
np.random.randn(5,6)

array([[-0.33624932, -1.67780852,  1.22237769,  0.88482258, -0.76706839,
         0.34009338],
       [-0.16893816, -0.16295108, -0.35846649, -0.3323731 , -0.73274823,
         0.17647211],
       [-2.00887033,  0.26343964, -0.96997398, -2.28551227,  0.06128909,
         0.67501799],
       [ 1.12303945, -0.98880483,  1.04875706,  0.35307241, -0.11817193,
        -1.2319041 ],
       [-1.89531152,  0.85965709, -0.58112359, -0.62430887,  0.98494797,
        -1.11124694]])

In [35]:
np.random.random_sample((5,6))

array([[0.16110762, 0.93832244, 0.37509142, 0.68719723, 0.16947745,
        0.13101682],
       [0.57763205, 0.07549324, 0.63700229, 0.84244027, 0.55893146,
        0.87978562],
       [0.38446723, 0.57894839, 0.55840155, 0.87609957, 0.82182445,
        0.20397123],
       [0.28824878, 0.23810118, 0.92713086, 0.08757575, 0.02728656,
        0.34533366],
       [0.11550789, 0.02748917, 0.67685487, 0.27239008, 0.20232581,
        0.83597696]])